### ISSUE TITLE
Cannot find module 'clear'

### ISSUE THREAD

**Issue by jankapunkt** [mlshv/exactify#1]
When installing globally via npm and running as described in the docs I get

```sh
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'clear' imported from /home/user/path/to/node_modules/exactify/lib/index.js
```

**Comment by mlshv** [comment]
Thank you for the feedback. I've fixed runtime dependencies. Try again please :-)

```shell
npm uninstall exactify -g
npm install exactify -g
```

Feel free to reopen the issue if the bug still exists
